// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
export const careersCategory = [
  {
    category: "Accounting",
    subcategory: [
      "Accounts Officers/Clerks",
      "Accounts Payable",
      "Accounts Receivable/Credit Control",
      "Analysis & Reporting",
      "Assistant Accountants",
      "Audit - External",
      "Audit - Internal",
      "Bookkeeping Services & Corporate Advisory",
      "Business Services & Corporate Advisory",
      "Company Secretaries",
      "Compliance & Risk",
      "Cost Accounting",
      "Financial Accounting & Reporting",
      "Financial Managers & Controllers",
      "Forensic Accounting & Investigation",
      "Insolvency & Corporate Recovery",
      "Inventory & Fixed Assets",
      "Management",
      "Management Accounting & Budgeting",
      "Payroll",
      "Strategy & Planning",
      "Systems Accounting & IT Audit",
      "Taxation",
      "Treasury",
      "Other",
    ],
  },
  {
    category: "Administration & Office Support",
    subcategory: [
      "Administrative Assistants",
      "Client & Sales Administration",
      "Contracts Administration",
      "Data Entry & Word Processing",
      "Office Management",
      "PA, EA & Secretarial",
      "Receptionists",
      "Records Management & Document Control",
      "Other",
    ],
  },
  { category: "Advertising, Arts & Media" },
  { category: "Banking & Financial Services" },
  { category: "Call Center & Customer Service" },
  { category: "CEO & General Management" },
  { category: "Community Service & Development" },
  { category: "Construction" },
  { category: "Consulting & Strategy" },
  { category: "Design & Architecture" },
  { category: "Education & Training" },
  { category: "Engineering" },
  { category: "Farming, Animals & Conservation" },
  { category: "Government & Defence" },
  { category: "Healthcare & Medical" },
  { category: "Hospitality & Tourism" },
  { category: "Human Resources & Recruitment" },
  { category: "Information & Communication Technology" },
  { category: "Insurance & Superannuation" },
  { category: "Legal" },
  { category: "Manufacturing, Transport & Logistics" },
  { category: "Marketing & Communications" },
  { category: "Minining, Resources & Energy" },
  { category: "Real Estate & Property" },
  { category: "Retail & Consumer Products" },
  { category: "Sales" },
  { category: "Science & Technology" },
  { category: "Self Employment" },
  { category: "Sport & Recreation" },
  { category: "Trades & Services" },
];

export const jobCategory = [
  { category: "Accountant", field: "Accounting" },
  { category: "Accounts Clerk", field: "Accounting" },
  { category: "Accounts Payable", field: "Accounting" },
  { category: "Accounts Receivable", field: "Accounting" },
];

export const educationCategory = [
  { category: "Digital Design", field: "Design" },
  { category: "Communication Design", field: "Design" },
  { category: "Fashion Design", field: "Design" },
  { category: "Industrial Design", field: "Design" },
];
