// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
export const careersCategory = [
  {
    category: "Unemployed / Graduate",
  },
  {
    category: "Accounting",
  },
  {
    category: "Administration & Office Support",
  },
  { category: "Advertising, Arts & Media" },
  { category: "Banking & Financial Services" },
  { category: "Call Center & Customer Service" },
  { category: "CEO & General Management" },
  { category: "Community Service & Development" },
  { category: "Construction" },
  { category: "Consulting & Strategy" },
  { category: "Design & Architecture" },
  { category: "Education & Training" },
  { category: "Engineering" },
  { category: "Farming, Animals & Conservation" },
  { category: "Government & Defence" },
  { category: "Healthcare & Medical" },
  { category: "Hospitality & Tourism" },
  { category: "Human Resources & Recruitment" },
  { category: "Information & Communication Technology" },
  { category: "Insurance & Superannuation" },
  { category: "Legal" },
  { category: "Manufacturing, Transport & Logistics" },
  { category: "Marketing & Communications" },
  { category: "Minining, Resources & Energy" },
  { category: "Real Estate & Property" },
  { category: "Retail & Consumer Products" },
  { category: "Sales" },
  { category: "Science & Technology" },
  { category: "Self Employment" },
  { category: "Sport & Recreation" },
  { category: "Trades & Services" },
];

export const jobCategory = [
  { category: "Unemployed / Graduate", field: "0" },
  { category: "Accounts Officers/Clerks", field: "Accounting" },
  { category: "Accounts payable", field: "Accounting" },
  { category: "Accounts Receivable/Credit Control", field: "Accounting" },
  { category: "Analysis & Reporting", field: "Accounting" },
  { category: "Assistant Accountant", field: "Accounting" },
  { category: "Audit - External", field: "Accounting" },
  { category: "Audit - Internal", field: "Accounting" },
  { category: "Bookkeeping & Small Practice Accounting", field: "Accounting" },
  { category: "Business Services & Corporate Advisory", field: "Accounting" },
  { category: "Company Secretaries", field: "Accounting" },
  { category: "Compliance & Risk", field: "Accounting" },
  { category: "Cost Accounting", field: "Accounting" },
  { category: "Financial Accounting & Reporting", field: "Accounting" },
  { category: "Financial Managers & Controllers", field: "Accounting" },
  { category: "Forensic Accounting & Investigation", field: "Accounting" },
  { category: "Insolvency & Corporate Recovery", field: "Accounting" },
  { category: "Inventory & Fixed Assets", field: "Accounting" },
  { category: "Management", field: "Accounting" },
  { category: "Management Accounting & Budgeting", field: "Accounting" },
  { category: "Payroll", field: "Accounting" },
  { category: "Strategy & Planning", field: "Accounting" },
  { category: "Systems Accounting & IT Audit", field: "Accounting" },
  { category: "Taxation", field: "Accounting" },
  { category: "Treasury", field: "Accounting" },
  { category: "Administrative Assistant", field: "Administration" },
  { category: "Client & Sales Administration", field: "Administration" },
  { category: "Contracts Administration", field: "Administration" },
  { category: "Data Entry & Word Processing", field: "Administration" },
  { category: "Office Management", field: "Administration" },
  { category: "PA, EA & Secretarial", field: "Administration" },
  { category: "Receptionists", field: "Administration" },
  {
    category: "Records Management & Document Control",
    field: "Administration",
  },
  {
    category: "Agency Account Management",
    field: "Adertisement, Arts & Media",
  },
  { category: "Art Director", field: "Adertisement, Arts & Media" },
  { category: "Editing & Publishing", field: "Adertisement, Arts & Media" },
  { category: "Event Management", field: "Adertisement, Arts & Media" },
  { category: "Journalism & Writing", field: "Adertisement, Arts & Media" },
  { category: "Management", field: "Adertisement, Arts & Media" },
  {
    category: "Media Strategy, Planning & Buying",
    field: "Adertisement, Arts & Media",
  },
  { category: "Performing Arts", field: "Adertisement, Arts & Media" },
  { category: "Photography", field: "Adertisement, Arts & Media" },
  { category: "Programming & Production", field: "Adertisement, Arts & Media" },
  { category: "Promotions", field: "Adertisement, Arts & Media" },
  {
    category: "Account & Relationship Management",
    field: "Banking & Financial Services",
  },
  { category: "Analysis & Reporting", field: "Banking & Financial Services" },
  { category: "Banking - Business", field: "Banking & Financial Services" },
  {
    category: "Banking - Corporate & Institutional",
    field: "Banking & Financial Services",
  },
  {
    category: "Banking - Retail/Branch",
    field: "Banking & Financial Services",
  },
  { category: "Client Services", field: "Banking & Financial Services" },
  { category: "Compliance & Risk", field: "Banking & Financial Services" },
  {
    category: "Corporate Finance & Investment Banking",
    field: "Banking & Financial Services",
  },
  { category: "Credit", field: "Banking & Financial Services" },
  { category: "Financial Planning", field: "Banking & Financial Services" },
  { category: "Funds Management", field: "Banking & Financial Services" },
  { category: "Management", field: "Banking & Financial Services" },
  { category: "Mortgages", field: "Banking & Financial Services" },
  { category: "Settlement", field: "Banking & Financial Services" },
  { category: "Stockbroking & Trading", field: "Banking & Financial Services" },
  { category: "Treasury", field: "Banking & Financial Services" },
  { category: "Collections", field: "Call Centre & Customer Service" },
  {
    category: "Customer Service - Call Centre",
    field: "Call Centre & Customer Service",
  },
  {
    category: "Customer Service - Customer Facing",
    field: "Call Centre & Customer Service",
  },
  { category: "Management & Support", field: "Call Centre & Customer Service" },
  { category: "Sales - Inbound", field: "Call Centre & Customer Service" },
  { category: "Sales - Outbound", field: "Call Centre & Customer Service" },
  {
    category: "Supervisors/Team Leaders",
    field: "Call Centre & Customer Service",
  },
  { category: "Board Appointments", field: "CEO & General Management" },
  { category: "CEO", field: "CEO & General Management" },
  { category: "COO & MD", field: "CEO & General Management" },
  {
    category: "General/Business Unit Manager",
    field: "CEO & General Management",
  },
  {
    category: "Aged & Disability Support",
    field: "Community Services & Development",
  },
  {
    category: "Child Welfare, Youth & Family Services",
    field: "Community Services & Development",
  },
  {
    category: "Community Development",
    field: "Community Services & Development",
  },
  {
    category: "Employment Services",
    field: "Community Services & Development",
  },
  { category: "Fundraising", field: "Community Services & Development" },
  {
    category: "Housing & Homelessness Services",
    field: "Community Services & Development",
  },
  {
    category: "Indigenous & Multicultural Services",
    field: "Community Services & Development",
  },
  { category: "Management", field: "Community Services & Development" },
  {
    category: "Volunteer Coordination & Support",
    field: "Community Services & Development",
  },
  { category: "Contracts Management", field: "Construction" },
  { category: "Estimating", field: "Construction" },
  { category: "Foreperson/Supervisors", field: "Construction" },
  { category: "Management", field: "Construction" },
  { category: "Planning & Scheduling", field: "Construction" },
  { category: "Plant & Machinery Operators", field: "Construction" },
  { category: "Project Management", field: "Construction" },
  { category: "Surveying", field: "Construction" },
  { category: "Analysts", field: "Consulting & Strategy" },
  { category: "Corporate Development", field: "Consulting & Strategy" },
  {
    category: "Environment & Sustainability Consulting",
    field: "Consulting & Strategy",
  },
  {
    category: "Management & Change Consulting",
    field: "Consulting & Strategy",
  },
  { category: "Policy", field: "Consulting & Strategy" },
  { category: "Strategy & Planning", field: "Consulting & Strategy" },
  { category: "Architectural Drafting", field: "Design & Architecture" },
  { category: "Architecture", field: "Design & Architecture" },
  { category: "Fashion & Textile Design", field: "Design & Architecture" },
  { category: "Graphic Design", field: "Design & Architecture" },
  { category: "Illustration & Animation", field: "Design & Architecture" },
  { category: "Industrial Design", field: "Design & Architecture" },
  { category: "Interior Design", field: "Design & Architecture" },
  { category: "Landscape Architecture", field: "Design & Architecture" },
  { category: "Urban Design & Planning", field: "Design & Architecture" },
  { category: "Web & Interaction Design", field: "Design & Architecture" },
  {
    category: "Childcare & Outside School Hours Care",
    field: "Education & Training",
  },
  {
    category: "Library Services & Information Management",
    field: "Education & Training",
  },
  { category: "Management - Schools", field: "Education & Training" },
  { category: "Management - Universities", field: "Education & Training" },
  { category: "Management - Vocational", field: "Education & Training" },
  { category: "Research & Fellowships", field: "Education & Training" },
  { category: "Student Services", field: "Education & Training" },
  { category: "Teaching - Early Childhood", field: "Education & Training" },
  { category: "Teaching - Primary", field: "Education & Training" },
  { category: "Teaching - Secondary", field: "Education & Training" },
  { category: "Teaching - Tertiary", field: "Education & Training" },
  { category: "Teaching - Vocational", field: "Education & Training" },
  { category: "Teaching Aides & Special Needs", field: "Education & Training" },
  { category: "Tutoring", field: "Education & Training" },
  {
    category: "Workplace Training & Assessment",
    field: "Education & Training",
  },
  { category: "Aerospace Engineering", field: "Engineering" },
  { category: "Automative Engineering", field: "Engineering" },
  { category: "Building Services Engineering", field: "Engineering" },
  { category: "Chemical Engineering", field: "Engineering" },
  { category: "Civil/Structural Engineering", field: "Engineering" },
  { category: "Electrical/Electronic Engineering", field: "Engineering" },
  { category: "Environmental Engineering", field: "Engineering" },
  { category: "Field Engineering", field: "Engineering" },
  { category: "Industrial Engineering", field: "Engineering" },
  { category: "Maintenance", field: "Engineering" },
  { category: "Management", field: "Engineering" },
  { category: "Materials Handling Engineering", field: "Engineering" },
  { category: "Mechanical Engineering", field: "Engineering" },
  { category: "Process Engineering", field: "Engineering" },
  { category: "Project Engineering", field: "Engineering" },
  { category: "Project Management", field: "Engineering" },
  { category: "Supervisors", field: "Engineering" },
  { category: "Systems Engineering", field: "Engineering" },
  { category: "Water & Waste Engineering", field: "Engineering" },
];

export const tertiaryEducationCategory = [
  { category: "Digital Design", field: "Design" },
  { category: "Communication Design", field: "Design" },
  { category: "Fashion Design", field: "Design" },
  { category: "Industrial Design", field: "Design" },
];

export const secondaryEducationCategory = [
  { category: "YEAR 9", field: "secondary", level: 9 },
  { category: "YEAR 10", field: "secondary", level: 10 },
  { category: "YEAR 11", field: "secondary", level: 11 },
  { category: "YEAR 12", field: "secondary", level: 12 },
  { category: "YEAR 13", field: "secondary", level: 13 },
  { category: "University", field: "tertiary", level: 14 },
  { category: "Trades", field: "tertiary", level: 14 },
];

export const uniCategory = [
  { category: "Harvard University", field: "US" },
  { category: "Massachusetts Institute of Technology", field: "US" },
  { category: "University of California, Los Angeles", field: "US" },
  { category: "Auckland University of Technology", field: "NZ" },
  { category: "University of Auckland", field: "NZ" },
  { category: "Massey University", field: "NZ" },
];

export const countryCategory = [
  { category: "United States of America" },
  { category: "New Zealand" },
  { category: "Australia" },
];

export const cultureCategory = [
  { category: "Straight", field: "Sexuality" },
  { category: "Homosexual", field: "Sexuality" },
  { category: "Bisexual", field: "Sexuality" },
  { category: "Male", field: "Gender" },
  { category: "Female", field: "Gender" },
  { category: "Binary", field: "Gender" },
  { category: "Non-binary", field: "Gender" },
];

export const lifeCategory = [
  { category: "Single", field: "Marital Status" },
  { category: "In a relationship", field: "Marital Status" },
  { category: "Married", field: "Marital Status" },
];
