export const careersCategory = [
  {
    category: "Unemployed / Graduate",
  },
  {
    category: "Accounting",
  },
  {
    category: "Administration & Office Support",
  },
  { category: "Advertising, Arts & Media" },
  { category: "Banking & Financial Services" },
  { category: "Call Center & Customer Service" },
  { category: "CEO & General Management" },
  { category: "Community Service & Development" },
  { category: "Construction" },
  { category: "Consulting & Strategy" },
  { category: "Design & Architecture" },
  { category: "Education & Training" },
  { category: "Engineering" },
  { category: "Farming, Animals & Conservation" },
  { category: "Government & Defence" },
  { category: "Healthcare & Medical" },
  { category: "Hospitality & Tourism" },
  { category: "Human Resources & Recruitment" },
  { category: "Information & Communication Technology" },
  { category: "Insurance & Superannuation" },
  { category: "Legal" },
  { category: "Manufacturing, Transport & Logistics" },
  { category: "Marketing & Communications" },
  { category: "Minining, Resources & Energy" },
  { category: "Real Estate & Property" },
  { category: "Retail & Consumer Products" },
  { category: "Sales" },
  { category: "Science & Technology" },
  { category: "Self Employment" },
  { category: "Sport & Recreation" },
  { category: "Trades & Services" },
];

export const jobCategory = [
  { category: "Unemployed / Graduate", field: "0" },
  { category: "Accounts Officers/Clerks", field: "Accounting" },
  { category: "Accounts payable", field: "Accounting" },
  { category: "Accounts Receivable/Credit Control", field: "Accounting" },
  { category: "Analysis & Reporting", field: "Accounting" },
  { category: "Assistant Accountant", field: "Accounting" },
  { category: "Audit - External", field: "Accounting" },
  { category: "Audit - Internal", field: "Accounting" },
  { category: "Bookkeeping & Small Practice Accounting", field: "Accounting" },
  { category: "Business Services & Corporate Advisory", field: "Accounting" },
  { category: "Company Secretaries", field: "Accounting" },
  { category: "Compliance & Risk", field: "Accounting" },
  { category: "Cost Accounting", field: "Accounting" },
  { category: "Financial Accounting & Reporting", field: "Accounting" },
  { category: "Financial Managers & Controllers", field: "Accounting" },
  { category: "Forensic Accounting & Investigation", field: "Accounting" },
  { category: "Insolvency & Corporate Recovery", field: "Accounting" },
  { category: "Inventory & Fixed Assets", field: "Accounting" },
  { category: "Management", field: "Accounting" },
  { category: "Management Accounting & Budgeting", field: "Accounting" },
  { category: "Payroll", field: "Accounting" },
  { category: "Strategy & Planning", field: "Accounting" },
  { category: "Systems Accounting & IT Audit", field: "Accounting" },
  { category: "Taxation", field: "Accounting" },
  { category: "Treasury", field: "Accounting" },
  { category: "Administrative Assistant", field: "Administration" },
  { category: "Client & Sales Administration", field: "Administration" },
  { category: "Contracts Administration", field: "Administration" },
  { category: "Data Entry & Word Processing", field: "Administration" },
  { category: "Office Management", field: "Administration" },
  { category: "PA, EA & Secretarial", field: "Administration" },
  { category: "Receptionists", field: "Administration" },
  {
    category: "Records Management & Document Control",
    field: "Administration",
  },
  {
    category: "Agency Account Management",
    field: "Adertisement, Arts & Media",
  },
  { category: "Art Director", field: "Adertisement, Arts & Media" },
  { category: "Editing & Publishing", field: "Adertisement, Arts & Media" },
  { category: "Event Management", field: "Adertisement, Arts & Media" },
  { category: "Journalism & Writing", field: "Adertisement, Arts & Media" },
  { category: "Management", field: "Adertisement, Arts & Media" },
  {
    category: "Media Strategy, Planning & Buying",
    field: "Adertisement, Arts & Media",
  },
  { category: "Performing Arts", field: "Adertisement, Arts & Media" },
  { category: "Photography", field: "Adertisement, Arts & Media" },
  { category: "Programming & Production", field: "Adertisement, Arts & Media" },
  { category: "Promotions", field: "Adertisement, Arts & Media" },
  {
    category: "Account & Relationship Management",
    field: "Banking & Financial Services",
  },
  { category: "Analysis & Reporting", field: "Banking & Financial Services" },
  { category: "Banking - Business", field: "Banking & Financial Services" },
  {
    category: "Banking - Corporate & Institutional",
    field: "Banking & Financial Services",
  },
  {
    category: "Banking - Retail/Branch",
    field: "Banking & Financial Services",
  },
  { category: "Client Services", field: "Banking & Financial Services" },
  { category: "Compliance & Risk", field: "Banking & Financial Services" },
  {
    category: "Corporate Finance & Investment Banking",
    field: "Banking & Financial Services",
  },
  { category: "Credit", field: "Banking & Financial Services" },
  { category: "Financial Planning", field: "Banking & Financial Services" },
  { category: "Funds Management", field: "Banking & Financial Services" },
  { category: "Management", field: "Banking & Financial Services" },
  { category: "Mortgages", field: "Banking & Financial Services" },
  { category: "Settlement", field: "Banking & Financial Services" },
  { category: "Stockbroking & Trading", field: "Banking & Financial Services" },
  { category: "Treasury", field: "Banking & Financial Services" },
  { category: "Collections", field: "Call Centre & Customer Service" },
  {
    category: "Customer Service - Call Centre",
    field: "Call Centre & Customer Service",
  },
  {
    category: "Customer Service - Customer Facing",
    field: "Call Centre & Customer Service",
  },
  { category: "Management & Support", field: "Call Centre & Customer Service" },
  { category: "Sales - Inbound", field: "Call Centre & Customer Service" },
  { category: "Sales - Outbound", field: "Call Centre & Customer Service" },
  {
    category: "Supervisors/Team Leaders",
    field: "Call Centre & Customer Service",
  },
  { category: "Board Appointments", field: "CEO & General Management" },
  { category: "CEO", field: "CEO & General Management" },
  { category: "COO & MD", field: "CEO & General Management" },
  {
    category: "General/Business Unit Manager",
    field: "CEO & General Management",
  },
  {
    category: "Aged & Disability Support",
    field: "Community Services & Development",
  },
  {
    category: "Child Welfare, Youth & Family Services",
    field: "Community Services & Development",
  },
  {
    category: "Community Development",
    field: "Community Services & Development",
  },
  {
    category: "Employment Services",
    field: "Community Services & Development",
  },
  { category: "Fundraising", field: "Community Services & Development" },
  {
    category: "Housing & Homelessness Services",
    field: "Community Services & Development",
  },
  {
    category: "Indigenous & Multicultural Services",
    field: "Community Services & Development",
  },
  { category: "Management", field: "Community Services & Development" },
  {
    category: "Volunteer Coordination & Support",
    field: "Community Services & Development",
  },
  { category: "Contracts Management", field: "Construction" },
  { category: "Estimating", field: "Construction" },
  { category: "Foreperson/Supervisors", field: "Construction" },
  { category: "Management", field: "Construction" },
  { category: "Planning & Scheduling", field: "Construction" },
  { category: "Plant & Machinery Operators", field: "Construction" },
  { category: "Project Management", field: "Construction" },
  { category: "Surveying", field: "Construction" },
  { category: "Analysts", field: "Consulting & Strategy" },
  { category: "Corporate Development", field: "Consulting & Strategy" },
  {
    category: "Environment & Sustainability Consulting",
    field: "Consulting & Strategy",
  },
  {
    category: "Management & Change Consulting",
    field: "Consulting & Strategy",
  },
  { category: "Policy", field: "Consulting & Strategy" },
  { category: "Strategy & Planning", field: "Consulting & Strategy" },
  { category: "Architectural Drafting", field: "Design & Architecture" },
  { category: "Architecture", field: "Design & Architecture" },
  { category: "Fashion & Textile Design", field: "Design & Architecture" },
  { category: "Graphic Design", field: "Design & Architecture" },
  { category: "Illustration & Animation", field: "Design & Architecture" },
  { category: "Industrial Design", field: "Design & Architecture" },
  { category: "Interior Design", field: "Design & Architecture" },
  { category: "Landscape Architecture", field: "Design & Architecture" },
  { category: "Urban Design & Planning", field: "Design & Architecture" },
  { category: "Web & Interaction Design", field: "Design & Architecture" },
  {
    category: "Childcare & Outside School Hours Care",
    field: "Education & Training",
  },
  {
    category: "Library Services & Information Management",
    field: "Education & Training",
  },
  { category: "Management - Schools", field: "Education & Training" },
  { category: "Management - Universities", field: "Education & Training" },
  { category: "Management - Vocational", field: "Education & Training" },
  { category: "Research & Fellowships", field: "Education & Training" },
  { category: "Student Services", field: "Education & Training" },
  { category: "Teaching - Early Childhood", field: "Education & Training" },
  { category: "Teaching - Primary", field: "Education & Training" },
  { category: "Teaching - Secondary", field: "Education & Training" },
  { category: "Teaching - Tertiary", field: "Education & Training" },
  { category: "Teaching - Vocational", field: "Education & Training" },
  { category: "Teaching Aides & Special Needs", field: "Education & Training" },
  { category: "Tutoring", field: "Education & Training" },
  {
    category: "Workplace Training & Assessment",
    field: "Education & Training",
  },
  { category: "Aerospace Engineering", field: "Engineering" },
  { category: "Automative Engineering", field: "Engineering" },
  { category: "Building Services Engineering", field: "Engineering" },
  { category: "Chemical Engineering", field: "Engineering" },
  { category: "Civil/Structural Engineering", field: "Engineering" },
  { category: "Electrical/Electronic Engineering", field: "Engineering" },
  { category: "Environmental Engineering", field: "Engineering" },
  { category: "Field Engineering", field: "Engineering" },
  { category: "Industrial Engineering", field: "Engineering" },
  { category: "Maintenance", field: "Engineering" },
  { category: "Management", field: "Engineering" },
  { category: "Materials Handling Engineering", field: "Engineering" },
  { category: "Mechanical Engineering", field: "Engineering" },
  { category: "Process Engineering", field: "Engineering" },
  { category: "Project Engineering", field: "Engineering" },
  { category: "Project Management", field: "Engineering" },
  { category: "Supervisors", field: "Engineering" },
  { category: "Systems Engineering", field: "Engineering" },
  { category: "Water & Waste Engineering", field: "Engineering" },
  { category: "Agronomy & Farm Services", field: "Farming, Animals & Conservation"},
  { category: "Conservation, Parks & Wildlife", field: "Farming, Animals & Conservation"},
  { category: "Farm Labour", field: "Farming, Animals & Conservation"},
  { category: "Farm Management", field: "Farming, Animals & Conservation"},
  { category: "Fishing & Aquaculture", field: "Farming, Animals & Conservation"},
  { category: "Horticulture", field: "Farming, Animals & Conservation"},
  { category: "Veterinary Services & Animal Welfare", field: "Farming, Animals & Conservation"},
  { category: "Winery & Viticulture", field: "Farming, Animals & Conservation"},
  { category: "Air Force", field: "Government & Defence"},
  { category: "Army", field: "Government & Defence"},
  { category: "Emergency Services", field: "Government & Defence"},
  { category: "Navy", field: "Government & Defence"},
  { category: "Police & Corrections", field: "Government & Defence"},
  { category: "Policy, Planning & Regulation", field: "Government & Defence"},
  { category: "Government", field: "Government & Defence"},
  { category: "Local Government", field: "Government & Defence"},
  { category: "Regional Council", field: "Government & Defence"},
  { category: "Ambulance/Paramedics", field: "Healthcare & Medical"},
  { category: "Chiropractic & Osteopathic", field: "Healthcare & Medical"},
  { category: "Clinical/Medical Research", field: "Healthcare & Medical"},
  { category: "Dental", field: "Healthcare & Medical"},
  { category: "Dieticians", field: "Healthcare & Medical"},
  { category: "Environmental Sciences", field: "Healthcare & Medical"},
  { category: "General practicioners", field: "Healthcare & Medical"},
  { category: "Management", field: "Healthcare & Medical"},
  { category: "Medical Administration", field: "Healthcare & Medical"},
  { category: "Medical Imaging", field: "Healthcare & Medical"},
  { category: "Medical Specialists", field: "Healthcare & Medical"},
  { category: "Natural Therapies & Alternative Medicine", field: "Healthcare & Medical"},
  { category: "Nursing - A&E, Critical Care & ICU", field: "Healthcare & Medical"},
  { category: "Nursing - Aged Care", field: "Healthcare & Medical"},
  { category: "Nursing - Community, Maternal & Child Health", field: "Healthcare & Medical"},
  { category: "Nursing - Educators & Facilitators", field: "Healthcare & Medical"},
  { category: "Nursing - General Medical & Surgical", field: "Healthcare & Medical"},
  { category: "Nursing - High Acuity", field: "Healthcare & Medical"},
  { category: "Nursing - Management", field: "Healthcare & Medical"},
  { category: "Nursing - Psych, Forensic & Correctional Health", field: "Healthcare & Medical"},
  { category: "Nursing - Theatre & Recovery", field: "Healthcare & Medical"},
  { category: "Optical", field: "Healthcare & Medical"},
  { category: "Pathology", field: "Healthcare & Medical"},
  { category: "Pharmaceuticals & Medical Devices", field: "Healthcare & Medical"},
  { category: "Pharmacy", field: "Healthcare & Medical"},
  { category: "Physiotheraphy, OT & Rehabilitation", field: "Healthcare & Medical"},
  { category: "Psychology, Counselling & Social Work", field: "Healthcare & Medical"},
  { category: "Residents & Registrars", field: "Healthcare & Medical"},
  { category: "Sales", field: "Healthcare & Medical"},
  { category: "Speech Theraphy", field: "Healthcare & Medical"},
  { category: "Airlines", field: "Hospitality & Tourism"},
  { category: "Bar & Beverage Staff", field: "Hospitality & Tourism"},
  { category: "Chef/Cooks", field: "Hospitality & Tourism"},
  { category: "Front Office & Guest Services", field: "Hospitality & Tourism"},
  { category: "Gaming", field: "Hospitality & Tourism"},
  { category: "Housekeeping", field: "Hospitality & Tourism"},
  { category: "Kitchen & Sandwich Hands", field: "Hospitality & Tourism"},
  { category: "Management", field: "Hospitality & Tourism"},
  { category: "Reservations", field: "Hospitality & Tourism"},
  { category: "Tour Guides", field: "Hospitality & Tourism"},
  { category: "Travel Agents/Consultants", field: "Hospitality & Tourism"},
  { category: "Waiting Staff", field: "Hospitality & Tourism"},
  { category: "Consulting & Generalist HR", field: "Human Resources & Recruitment"},
  { category: "Industrial & Employee relations", field: "Human Resources & Recruitment"},
  { category: "Management - Agency", field: "Human Resources & Recruitment"},
  { category: "Management - Internal", field: "Human Resources & Recruitment"},
  { category: "Occupational Health & Safety", field: "Human Resources & Recruitment"},
  { category: "Organisational Development", field: "Human Resources & Recruitment"},
  { category: "Recruitment - Agency", field: "Human Resources & Recruitment"},
  { category: "Remuneration & Benefits", field: "Human Resources & Recruitment"},
  { category: "Training & Development", field: "Human Resources & Recruitment"},
  { category: "Architects", field: "Information & Communication Technology"},
  { category: "Business/System Analysts", field: "Information & Communication Technology"},
  { category: "Computer Operators", field: "Information & Communication Technology"},
  { category: "Consultants", field: "Information & Communication Technology"},
  { category: "Database Development & Administration", field: "Information & Communication Technology"},
  { category: "Developers/Programmers", field: "Information & Communication Technology"},
  { category: "Engineering - Hardware", field: "Information & Communication Technology"},
  { category: "Engineering - Network", field: "Information & Communication Technology"},
  { category: "Engineering - Software", field: "Information & Communication Technology"},
  { category: "Help Desk & IT Support", field: "Information & Communication Technology"},
  { category: "Management", field: "Information & Communication Technology"},
  { category: "Networks & Systems Administration", field: "Information & Communication Technology"},
  { category: "Product Management & Development", field: "Information & Communication Technology"},
  { category: "Programme & Project Management", field: "Information & Communication Technology"},
  { category: "Sales - Pre & Post", field: "Information & Communication Technology"},
  { category: "Security", field: "Information & Communication Technology"},
  { category: "Team Leaders", field: "Information & Communication Technology"},
  { category: "Technical Writing", field: "Information & Communication Technology"},
  { category: "Telecommunications", field: "Information & Communication Technology"},
  { category: "Testing & Quality Assurance", field: "Information & Communication Technology"},
  { category: "Web Development & Production", field: "Information & Communication Technology"},
  { category: "Actuarial", field: "Insurance & Superannuation"},
  { category: "Assessment", field: "Insurance & Superannuation"},
  { category: "Brokerage", field: "Insurance & Superannuation"},
  { category: "Claims", field: "Insurance & Superannuation"},
  { category: "Fund Administration", field: "Insurance & Superannuation"},
  { category: "Management", field: "Insurance & Superannuation"},
  { category: "Risk Consulting", field: "Insurance & Superannuation"},
  { category: "Superannuation", field: "Insurance & Superannuation"},
  { category: "Underwriting", field: "Insurance & Superannuation"},
  { category: "Workers' Compensation", field: "Insurance & Superannuation"},
  { category: "Banking & Finance Law", field: "Legal"},
  { category: "Construction Law", field: "Legal"},
  { category: "Corporate & Commercial Law", field: "Legal"},
  { category: "Criminal & Civil Law", field: "Legal"},
  { category: "Environment & Planning Law", field: "Legal"},
  { category: "Family Law", field: "Legal"},
  { category: "Generalists - In-house", field: "Legal"},
  { category: "Generalists - Law Firm", field: "Legal"},
  { category: "Industrial Relations & Employment Law", field: "Legal"},
  { category: "Insurance & Superannuation Law", field: "Legal"},
  { category: "Intellectual Property Law", field: "Legal"},
  { category: "Law Clerks & Paralegals", field: "Legal"},
  { category: "Legal Practice Management", field: "Legal"},
  { category: "Legal Secretaries", field: "Legal"},
  { category: "Litigation & Dispute Resolution", field: "Legal"},
  { category: "Personal Injury Law", field: "Legal"},
  { category: "Property Law", field: "Legal"},
  { category: "Tax Law", field: "Legal"},
  { category: "Analysis & Reporting", field: "Manufacturing, Transport & Logistics"},
  { category: "Assembly & Process Work", field: "Manufacturing, Transport & Logistics"},
  { category: "Aviation Services", field: "Manufacturing, Transport & Logistics"},
  { category: "Couriers, Drivers & Postal Services", field: "Manufacturing, Transport & Logistics"},
  { category: "Fleet Management", field: "Manufacturing, Transport & Logistics"},
  { category: "Freight/Cargo Forwarding", field: "Manufacturing, Transport & Logistics"},
  { category: "Import/Export & Customs", field: "Manufacturing, Transport & Logistics"},
  { category: "Machine Operators", field: "Manufacturing, Transport & Logistics"},
  { category: "Management", field: "Manufacturing, Transport & Logistics"},
  { category: "Pattern Makers & Garment Technicians", field: "Manufacturing, Transport & Logistics"},
  { category: "Pickers & Packers", field: "Manufacturing, Transport & Logistics"},
  { category: "Production, Planning & Scheduling", field: "Manufacturing, Transport & Logistics"},
  { category: "Public Transport & Taxi Services", field: "Manufacturing, Transport & Logistics"},
  { category: "Purchasing, Procurement & Inventory", field: "Manufacturing, Transport & Logistics"},
  { category: "Quality Assurance & Control", field: "Manufacturing, Transport & Logistics"},
  { category: "Rail & Maritime Transport", field: "Manufacturing, Transport & Logistics"},
  { category: "Road Transport", field: "Manufacturing, Transport & Logistics"},
  { category: "Team Leaders/Supervisors", field: "Manufacturing, Transport & Logistics"},
  { category: "Warehousing, Storage & Distribution", field: "Manufacturing, Transport & Logistics"},
  { category: "Brand Management", field: "Marketing & Communications"},
  { category: "Digital & Search Marketing", field: "Marketing & Communications"},
  { category: "Direct Marketing & CRM", field: "Marketing & Communications"},
  { category: "Event Management", field: "Marketing & Communications"},
  { category: "Internal Communications", field: "Marketing & Communications"},
  { category: "Management", field: "Marketing & Communications"},
  { category: "Market Research & Analysis", field: "Marketing & Communications"},
  { category: "Marketing Assistants/Coordinators", field: "Marketing & Communications"},
  { category: "Marketing Communications", field: "Marketing & Communications"},
  { category: "Product Management & Development", field: "Marketing & Communications"},
  { category: "Public Relations & Corporate Affairs", field: "Marketing & Communications"},
  { category: "Trade Marketing", field: "Marketing & Communications"},
  { category: "Analysis & Reporting", field: "Mining, Resources & Energy"},
  { category: "Health, Safety & Environment", field: "Mining, Resources & Energy"},
  { category: "Management", field: "Mining, Resources & Energy"},
  { category: "Mining - Drill & Blast", field: "Mining, Resources & Energy"},
  { category: "Mining - Engineering & Maintenance", field: "Mining, Resources & Energy"},
  { category: "Mining - Exploration & Geoscience", field: "Mining, Resources & Energy"},
  { category: "Mining - Operations", field: "Mining, Resources & Energy"},
  { category: "Mining - Processing", field: "Mining, Resources & Energy"},
  { category: "Natural Resources & Water", field: "Mining, Resources & Energy"},
  { category: "Oil & Gas - Drilling", field: "Mining, Resources & Energy"},
  { category: "Oil & Gas - Engineering & Maintenance", field: "Mining, Resources & Energy"},
  { category: "Oil & Gas - Exploration & Geoscience", field: "Mining, Resources & Energy"},
  { category: "Oil & Gas - Operations", field: "Mining, Resources & Energy"},
  { category: "Oil & Gas - Production & Refinement", field: "Mining, Resources & Energy"},
  { category: "Power Generation & Distribution", field: "Mining, Resources & Energy"},
  { category: "Surveying", field: "Mining, Resources & Energy"},
  { category: "Administration", field: "Real Estate & Property"},
  { category: "Analysts", field: "Real Estate & Property"},
  { category: "Body Corporate & Facilities Management", field: "Real Estate & Property"},
  { category: "Commercial Sales, Leasing & Property Mgmt", field: "Real Estate & Property"},
  { category: "Residential Leasing & Property Management", field: "Real Estate & Property"},
  { category: "Residential Sales", field: "Real Estate & Property"},
  { category: "Retail & Property Development", field: "Real Estate & Property"},
  { category: "Valuation", field: "Real Estate & Property"},
  { category: "Buying", field: "Retail & Consumer Products"},
  { category: "Management - Area/Multi-site", field: "Retail & Consumer Products"},
  { category: "Management - Department/Assistant", field: "Retail & Consumer Products"},
  { category: "Management - Store", field: "Retail & Consumer Products"},
  { category: "Merchandisers", field: "Retail & Consumer Products"},
  { category: "Planning", field: "Retail & Consumer Products"},
  { category: "Retail Assistants", field: "Retail & Consumer Products"},
  
];

export const tertiaryEducationCategory = [
  { category: "Digital Design", field: "Design" },
  { category: "Communication Design", field: "Design" },
  { category: "Fashion Design", field: "Design" },
  { category: "Industrial Design", field: "Design" },
];

export const secondaryEducationCategory = [
  { category: "YEAR 9", field: "secondary", level: 9 },
  { category: "YEAR 10", field: "secondary", level: 10 },
  { category: "YEAR 11", field: "secondary", level: 11 },
  { category: "YEAR 12", field: "secondary", level: 12 },
  { category: "YEAR 13", field: "secondary", level: 13 },
  { category: "University", field: "tertiary", level: 14 },
  { category: "Apprenticeship", field: "tertiary", level: 14 },
];

export const uniCategory = [
  { category: "Auckland University of Technology", field: "" },
  { category: "Lincoln University", field: "" },
  { category: "Massey University", field: "" },
  { category: "University of Auckland", field: "" },
  { category: "University of Canterbury", field: "" },
  { category: "University of Otago", field: "" },
  { category: "University of Waikato", field: "" },
  { category: "Victoria University of Wellington", field: "" },
];

export const countryCategory = [
  { category: "Afghanistan", code: "AF" },
  { category: "Åland Islands", code: "AX" },
  { category: "Albania", code: "AL" },
  { category: "Algeria", code: "DZ" },
  { category: "American Samoa", code: "AS" },
  { category: "Andorra", code: "AD" },
  { category: "Angola", code: "AO" },
  { category: "Anguilla", code: "AI" },
  { category: "Antarctica", code: "AQ" },
  { category: "Antigua and Barbuda", code: "AG" },
  { category: "Argentina", code: "AR" },
  { category: "Armenia", code: "AM" },
  { category: "Aruba", code: "AW" },
  { category: "Australia", code: "AU" },
  { category: "Austria", code: "AT" },
  { category: "Azerbaijan", code: "AZ" },
  { category: "Bahamas", code: "BS" },
  { category: "Bahrain", code: "BH" },
  { category: "Bangladesh", code: "BD" },
  { category: "Barbados", code: "BB" },
  { category: "Belarus", code: "BY" },
  { category: "Belgium", code: "BE" },
  { category: "Belize", code: "BZ" },
  { category: "Benin", code: "BJ" },
  { category: "Bermuda", code: "BM" },
  { category: "Bhutan", code: "BT" },
  { category: "Bolivia", code: "BO" },
  { category: "Bosnia and Herzegovina", code: "BA" },
  { category: "Botswana", code: "BW" },
  { category: "Bouvet Island", code: "BV" },
  { category: "Brazil", code: "BR" },
  { category: "British Indian Ocean Territory", code: "IO" },
  { category: "Brunei Darussalam", code: "BN" },
  { category: "Bulgaria", code: "BG" },
  { category: "Burkina Faso", code: "BF" },
  { category: "Burundi", code: "BI" },
  { category: "Cambodia", code: "KH" },
  { category: "Cameroon", code: "CM" },
  { category: "Canada", code: "CA" },
  { category: "Cape Verde", code: "CV" },
  { category: "Cayman Islands", code: "KY" },
  { category: "Central African Republic", code: "CF" },
  { category: "Chad", code: "TD" },
  { category: "Chile", code: "CL" },
  { category: "China", code: "CN" },
  { category: "Christmas Island", code: "CX" },
  { category: "Cocos (Keeling) Islands", code: "CC" },
  { category: "Colombia", code: "CO" },
  { category: "Comoros", code: "KM" },
  { category: "Congo", code: "CG" },
  { category: "Congo, The Democratic Republic of the", code: "CD" },
  { category: "Cook Islands", code: "CK" },
  { category: "Costa Rica", code: "CR" },
  { category: "Cote D'Ivoire", code: "CI" },
  { category: "Croatia", code: "HR" },
  { category: "Cuba", code: "CU" },
  { category: "Cyprus", code: "CY" },
  { category: "Czech Republic", code: "CZ" },
  { category: "Denmark", code: "DK" },
  { category: "Djibouti", code: "DJ" },
  { category: "Dominica", code: "DM" },
  { category: "Dominican Republic", code: "DO" },
  { category: "Ecuador", code: "EC" },
  { category: "Egypt", code: "EG" },
  { category: "El Salvador", code: "SV" },
  { category: "Equatorial Guinea", code: "GQ" },
  { category: "Eritrea", code: "ER" },
  { category: "Estonia", code: "EE" },
  { category: "Ethiopia", code: "ET" },
  { category: "Falkland Islands (Malvinas)", code: "FK" },
  { category: "Faroe Islands", code: "FO" },
  { category: "Fiji", code: "FJ" },
  { category: "Finland", code: "FI" },
  { category: "France", code: "FR" },
  { category: "French Guiana", code: "GF" },
  { category: "French Polynesia", code: "PF" },
  { category: "French Southern Territories", code: "TF" },
  { category: "Gabon", code: "GA" },
  { category: "Gambia", code: "GM" },
  { category: "Georgia", code: "GE" },
  { category: "Germany", code: "DE" },
  { category: "Ghana", code: "GH" },
  { category: "Gibraltar", code: "GI" },
  { category: "Greece", code: "GR" },
  { category: "Greenland", code: "GL" },
  { category: "Grenada", code: "GD" },
  { category: "Guadeloupe", code: "GP" },
  { category: "Guam", code: "GU" },
  { category: "Guatemala", code: "GT" },
  { category: "Guernsey", code: "GG" },
  { category: "Guinea", code: "GN" },
  { category: "Guinea-Bissau", code: "GW" },
  { category: "Guyana", code: "GY" },
  { category: "Haiti", code: "HT" },
  { category: "Heard Island and Mcdonald Islands", code: "HM" },
  { category: "Holy See (Vatican City State)", code: "VA" },
  { category: "Honduras", code: "HN" },
  { category: "Hong Kong", code: "HK" },
  { category: "Hungary", code: "HU" },
  { category: "Iceland", code: "IS" },
  { category: "India", code: "IN" },
  { category: "Indonesia", code: "ID" },
  { category: "Iran, Islamic Republic Of", code: "IR" },
  { category: "Iraq", code: "IQ" },
  { category: "Ireland", code: "IE" },
  { category: "Isle of Man", code: "IM" },
  { category: "Israel", code: "IL" },
  { category: "Italy", code: "IT" },
  { category: "Jamaica", code: "JM" },
  { category: "Japan", code: "JP" },
  { category: "Jersey", code: "JE" },
  { category: "Jordan", code: "JO" },
  { category: "Kazakhstan", code: "KZ" },
  { category: "Kenya", code: "KE" },
  { category: "Kiribati", code: "KI" },
  { category: "Korea, Democratic People'S Republic of", code: "KP" },
  { category: "Korea, Republic of", code: "KR" },
  { category: "Kuwait", code: "KW" },
  { category: "Kyrgyzstan", code: "KG" },
  { category: "Lao People'S Democratic Republic", code: "LA" },
  { category: "Latvia", code: "LV" },
  { category: "Lebanon", code: "LB" },
  { category: "Lesotho", code: "LS" },
  { category: "Liberia", code: "LR" },
  { category: "Libyan Arab Jamahiriya", code: "LY" },
  { category: "Liechtenstein", code: "LI" },
  { category: "Lithuania", code: "LT" },
  { category: "Luxembourg", code: "LU" },
  { category: "Macao", code: "MO" },
  { category: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { category: "Madagascar", code: "MG" },
  { category: "Malawi", code: "MW" },
  { category: "Malaysia", code: "MY" },
  { category: "Maldives", code: "MV" },
  { category: "Mali", code: "ML" },
  { category: "Malta", code: "MT" },
  { category: "Marshall Islands", code: "MH" },
  { category: "Martinique", code: "MQ" },
  { category: "Mauritania", code: "MR" },
  { category: "Mauritius", code: "MU" },
  { category: "Mayotte", code: "YT" },
  { category: "Mexico", code: "MX" },
  { category: "Micronesia, Federated States of", code: "FM" },
  { category: "Moldova, Republic of", code: "MD" },
  { category: "Monaco", code: "MC" },
  { category: "Mongolia", code: "MN" },
  { category: "Montserrat", code: "MS" },
  { category: "Morocco", code: "MA" },
  { category: "Mozambique", code: "MZ" },
  { category: "Myanmar", code: "MM" },
  { category: "Namibia", code: "NA" },
  { category: "Nauru", code: "NR" },
  { category: "Nepal", code: "NP" },
  { category: "Netherlands", code: "NL" },
  { category: "Netherlands Antilles", code: "AN" },
  { category: "New Caledonia", code: "NC" },
  { category: "New Zealand", code: "NZ" },
  { category: "Nicaragua", code: "NI" },
  { category: "Niger", code: "NE" },
  { category: "Nigeria", code: "NG" },
  { category: "Niue", code: "NU" },
  { category: "Norfolk Island", code: "NF" },
  { category: "Northern Mariana Islands", code: "MP" },
  { category: "Norway", code: "NO" },
  { category: "Oman", code: "OM" },
  { category: "Pakistan", code: "PK" },
  { category: "Palau", code: "PW" },
  { category: "Palestinian Territory, Occupied", code: "PS" },
  { category: "Panama", code: "PA" },
  { category: "Papua New Guinea", code: "PG" },
  { category: "Paraguay", code: "PY" },
  { category: "Peru", code: "PE" },
  { category: "Philippines", code: "PH" },
  { category: "Pitcairn", code: "PN" },
  { category: "Poland", code: "PL" },
  { category: "Portugal", code: "PT" },
  { category: "Puerto Rico", code: "PR" },
  { category: "Qatar", code: "QA" },
  { category: "Reunion", code: "RE" },
  { category: "Romania", code: "RO" },
  { category: "Russian Federation", code: "RU" },
  { category: "RWANDA", code: "RW" },
  { category: "Saint Helena", code: "SH" },
  { category: "Saint Kitts and Nevis", code: "KN" },
  { category: "Saint Lucia", code: "LC" },
  { category: "Saint Pierre and Miquelon", code: "PM" },
  { category: "Saint Vincent and the Grenadines", code: "VC" },
  { category: "Samoa", code: "WS" },
  { category: "San Marino", code: "SM" },
  { category: "Sao Tome and Principe", code: "ST" },
  { category: "Saudi Arabia", code: "SA" },
  { category: "Senegal", code: "SN" },
  { category: "Serbia and Montenegro", code: "CS" },
  { category: "Seychelles", code: "SC" },
  { category: "Sierra Leone", code: "SL" },
  { category: "Singapore", code: "SG" },
  { category: "Slovakia", code: "SK" },
  { category: "Slovenia", code: "SI" },
  { category: "Solomon Islands", code: "SB" },
  { category: "Somalia", code: "SO" },
  { category: "South Africa", code: "ZA" },
  { category: "South Georgia and the South Sandwich Islands", code: "GS" },
  { category: "Spain", code: "ES" },
  { category: "Sri Lanka", code: "LK" },
  { category: "Sudan", code: "SD" },
  { category: "Suriname", code: "SR" },
  { category: "Svalbard and Jan Mayen", code: "SJ" },
  { category: "Swaziland", code: "SZ" },
  { category: "Sweden", code: "SE" },
  { category: "Switzerland", code: "CH" },
  { category: "Syrian Arab Republic", code: "SY" },
  { category: "Taiwan, Province of China", code: "TW" },
  { category: "Tajikistan", code: "TJ" },
  { category: "Tanzania, United Republic of", code: "TZ" },
  { category: "Thailand", code: "TH" },
  { category: "Timor-Leste", code: "TL" },
  { category: "Togo", code: "TG" },
  { category: "Tokelau", code: "TK" },
  { category: "Tonga", code: "TO" },
  { category: "Trinidad and Tobago", code: "TT" },
  { category: "Tunisia", code: "TN" },
  { category: "Turkey", code: "TR" },
  { category: "Turkmenistan", code: "TM" },
  { category: "Turks and Caicos Islands", code: "TC" },
  { category: "Tuvalu", code: "TV" },
  { category: "Uganda", code: "UG" },
  { category: "Ukraine", code: "UA" },
  { category: "United Arab Emirates", code: "AE" },
  { category: "United Kingdom", code: "GB" },
  { category: "United States", code: "US" },
  { category: "United States Minor Outlying Islands", code: "UM" },
  { category: "Uruguay", code: "UY" },
  { category: "Uzbekistan", code: "UZ" },
  { category: "Vanuatu", code: "VU" },
  { category: "Venezuela", code: "VE" },
  { category: "Viet Nam", code: "VN" },
  { category: "Virgin Islands, British", code: "VG" },
  { category: "Virgin Islands, U.S.", code: "VI" },
  { category: "Wallis and Futuna", code: "WF" },
  { category: "Western Sahara", code: "EH" },
  { category: "Yemen", code: "YE" },
  { category: "Zambia", code: "ZM" },
  { category: "Zimbabwe", code: "ZW" },
];

export const cultureCategory = [
  { category: "Straight", field: "Sexuality" },
  { category: "Homosexual", field: "Sexuality" },
  { category: "Bisexual", field: "Sexuality" },
  { category: "Male", field: "Gender" },
  { category: "Female", field: "Gender" },
  { category: "Binary", field: "Gender" },
  { category: "Non-binary", field: "Gender" },
];

export const lifeCategory = [
  { category: "Obese", field: "Health" },
  { category: "Skinny", field: "Health" },
  { category: "Fit", field: "Health" },
  { category: "Vegan", field: "Diet" },
  { category: "Carnivore", field: "Diet" },
  { category: "Keto", field: "Diet" },
  { category: "Single", field: "Marital Status" },
  { category: "In a relationship", field: "Marital Status" },
  { category: "Married", field: "Marital Status" },
];
