// USER AUTH
export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_END = "ADD_USER_END";

// EXPERIENCE ACTIONS
export const ADD_EXPERIENCE_START = "ADD_EXPERIENCE_START";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";
export const ADD_EXPERIENCE_END = "ADD_EXPERIENCE_END";

