// USER AUTH
export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";
export const ADD_USER_END = "ADD_USER_END";

// EXPERIENCE ACTIONS
export const ADD_EXPERIENCE_START = "EXPERIENCE_FLOW_START";
export const ADD_EXPERIENCE_SUCCESS = "EXPERIENCE_FLOW_SUCCESS";
export const ADD_EXPERIENCE_FAIL = "EXPERIENCE_FLOW_FAIL";
export const ADD_EXPERIENCE_END = "EXPERIENCE_FLOW_END";

export const GET_EXPERIENCES_START = "GET_EXPERIENCES_START";
export const GET_EXPERIENCES_SUCCESS = "GET_EXPERIENCES_SUCCESS";
export const GET_EXPERIENCES_FAIL = "GET_EXPERIENCES_FAIL";
export const GET_EXPERIENCES_END = "GET_EXPERIENCES_END";
export const RECEIVE_EXPERIENCES = "RECEIVE_EXPERIENCES"

